github.com:
    users:
        r14r:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: r14r
